github.com:
    users:
        r14r:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: r14r
